export default [{
    img: "./common/img/main_sec03_img05.jpg",
    subject: "에이블에이젼시",
    projuctType: "반응형",
    subtxt: "모델 에이젼시 홈페이지 리뉴얼 제작",
    link: "https://ableplanning.co.kr/",
    percent: "퍼블리싱 100%",
  }, 
  {
    img: "./common/img/main_sec03_img05.jpg",
    subject: "에이블에이젼시",
    projuctType: "반응형",
    subtxt: "모델 에이젼시 홈페이지 리뉴얼 제작",
    link: "https://ableplanning.co.kr/",
    percent: "퍼블리싱 100%",
  }, {
    img: "./common/img/main_sec03_img05.jpg",
    subject: "에이블에이젼시",
    projuctType: "반응형",
    subtxt: "모델 에이젼시 홈페이지 리뉴얼 제작",
    link: "https://ableplanning.co.kr/",
    percent: "퍼블리싱 100%",
  }, {
    img: "./common/img/main_sec03_img05.jpg",
    subject: "에이블에이젼시",
    projuctType: "반응형",
    subtxt: "모델 에이젼시 홈페이지 리뉴얼 제작",
    link: "https://ableplanning.co.kr/",
    percent: "퍼블리싱 100%",
  }, {
    img: "./common/img/main_sec03_img05.jpg",
    subject: "에이블에이젼시",
    projuctType: "반응형",
    subtxt: "모델 에이젼시 홈페이지 리뉴얼 제작",
    link: "https://ableplanning.co.kr/",
    percent: "퍼블리싱 100%",
  },
];