export default [
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
  {
    img: "01.jpg",
    subject: "제목입니다",
    subtxt: "내용입니다",
    link: "www.naver.come",
  },
];
